# action.yml
name: 'upgrade-lean'
description: 'update master to the latest Lean/mathlib if compatible'
inputs:
  access-token:
    description: 'GitHub PAT to create issue'
    required: true
  remote:
    description: 'Which remote to push to'
    required: false
    default: 'origin'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ github.repository }}
    - ${{ inputs.access-token }}
    - ${{ inputs.remote }}